### ISSUE TITLE
代码错误 + 请教

### ISSUE THREAD

**Issue by Dr-Harris** [huangruichang/treex#2]
https://github.com/huangruichang/treex/blob/master/app/src/components/index.js
11行导出变量应该是`DiffLine`吧

还想请教一个nodegit的问题。
我想像vscode那样，通过整个文件的内容来展示修改的内容。您现在的项目中通过ConvenientHunk和DiffLine只能得到更改前后三行的内容。是否有什么思路呢？

我想要的diff展示
![TIM截图20200115164047](https://user-images.githubusercontent.com/22830171/72418474-daf02180-37b5-11ea-9fde-d14c9ba01895.png)

**Comment by huangruichang** [comment]
@Dr-Harris 三行的内容能否截图并且提供这个项目的链接给我？我把项目加载到里面试试看

**Comment by Dr-Harris** [comment]
https://github.com/huangruichang/treex/blob/master/app/src/helpers/index.js#L158
这个方法得到的diffLines就是前后三行的内容

![image](https://user-images.githubusercontent.com/22830171/72424329-c06f7580-37c0-11ea-8977-7973589069b0.png)

**Comment by Dr-Harris** [comment]
你的diff视图的展示，就是基于这种结果的

**Comment by huangruichang** [comment]
@Dr-Harris 我懂你的意思了，git 本身就是返回这种 diff 结果，你需要的那种效果应该是 ide 或者客户端把这些 diff 匹配到原文件上显示的。

**Comment by Dr-Harris** [comment]
好吧。看来这种功能需要自己来做，谢谢了
